movie_review_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('reviews.urls')),
    url(r'^admin/', admin.site.urls),
]

reviews/urls.py
from django.conf.urls import url
from . import views

app_name = 'reviews'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

reviews/models.py
from __future__ import unicode_literals

from django.db import models


class Movie(models.Model):
    movie_text = models.CharField(max_length = 20)
    movie_year = models.IntegerField(default = 0)
    def __str__(self):
        return self.movie_text
        
class Genre(models.Model):
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)
    genre_text = models.CharField(max_length=15, null=True)
    def __str__(self):
        return self.genre_text
        
class Actor(models.Model):
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)
    actor_text = models.CharField(max_length=35, null=True)
    def __str__(self):
        return self.actor_text
        
class Rating(models.Model):
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)
    rating_text = models.CharField(max_length=10)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.rating_text 
    
class Garbage(models.Model):
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)
    garbage_text = models.CharField(max_length=10)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.garbage_text 

reviews/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from .models import Movie, Genre, Actor, Rating

class IndexView(generic.ListView):
    template_name = 'reviews/index.html'
    context_object_name = 'movie_list'

    def get_queryset(self):
        return Movie.objects.order_by('movie_text')

class DetailView(generic.DetailView):
    model = Movie
    template_name = 'reviews/detail.html'

class ResultsView(generic.DetailView):
    model = Movie
    template_name = 'reviews/results.html'
    
def vote(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    try:
        selected_garbage = movie.garbage_set.get(pk=request.POST['garbage'])
    except (KeyError, Rating.DoesNotExist):
        return render(request, 'reviews/detail.html', {
            'movie': movie,
            'error_message': "You didn't select a rating.",
        })
    else:
        selected_garbage.votes += 1
        selected_garbage.save()
        return HttpResponseRedirect(reverse('reviews:results', args=(movie.id)))

reviews/templates/reviews/detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'reviews/style.css' %}" />

<h1>{{ movie.movie_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'reviews:vote' movie.id %}" method="post">
{% csrf_token %}
{% for garbage in movie.garbage_set.all %}
    <input type="radio" name="rating" id="garbage{{ forloop.counter }}" value="{{ garbage.id }}" />
    <label for="garbage{{ forloop.counter }}">{{ garbage.garbage_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote Here" />
</form>

reviews/templates/reviews/index.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">

    <title>(Movie Reviews)</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'reviews/style.css' %}" />
</head>

<body>
    <h1>Please pick from the movies below to rate them.</h1>
    <form>
        {% if movie_list %}
            {% for movie in movie_list %}
                <a href="{% url 'reviews:detail' movie.id %}">{{ movie.movie_text }}</a>
                <p>
                    Year Released: {{ movie.movie_year }} <br>
                    Genre: {{ move.genre_text }} <br>
                    Main Actor(s): {{ movie.actor_text }} <br>
                </p>
                <br>
            {% endfor %}
        {% else %}
            <p>No movies are available.</p>
        {% endif %}
    </form>
</body>
</html>

reviews/templates/reviews/results.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'reviews/style.css' %}" />

<h1>{{ movie.movie_text }}</h1>

<ul>
    {% for garbage in movie.garbage_set.all %}
        <li>{{ garbage.garbage_text }} -- {{ garbage.votes }} vote{{ garbage.votes|pluralize }}</li>
    {% endfor %}
</ul>
<br>
<a href="{% url 'reviews:index' %}">Pick another movie.</a>